/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springboot;
/*
import org.junit.Test;
import org.junit.*;
import org.junit.runner.*;
import org.springframework.test.context.junit4.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.mock.mockito.*;

@SpringBootTest
public class AppTest {

    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void testGetCityList() {
        MainController mainController = new MainController();
        Iterable<City> cities = mainController.getAllCities();
        assertEquals(1, 1);
    }
}
*/