/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springboot;
import springboot.MainController;
import springboot
import org.junit.Test;
import static org.junit.Assert.*;
@RunWith(App.class)
@SpringBootTest
public class AppTest {
    /*
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }*/
    @Test
    public void testGetCityList() {
        MainController mainController = new MainController();
        Iterable<City> cities = mainController.getAllCities();
        assertEquals(1, 1);
    }
}
